:toc:

= Documentation
Kadwalon Lobet, Guillaume de Maricourt.

== Project description
Project is around a low consumption control card, the Apollo 4 model.
This card is being use in order to record populations of birds 

== Objective
The problematic is around the energy consumption of the card
We are trying a method from the project EARLYBIRD https://

== Devices used
In order to work with the Apollo card, multiple devices were used:

* A TENMA progammable power supply, capable of providing level of voltage required for the card, see ''Emulator/PVEmu.py''
** Code are in majority from https://github.com/mbriday/PVEmu/tree/main
* The amperemeter included in the Power Profiler Kit 2 from Nordic, see ''Emulator/PPKemu.py''
* A Keysight Oscilloscope, in main case considered as a usbtmc device

== Main files
There is two main file:

* ''Main.py'' a simpler version to show how emulators are used
* ''Main_UI.py'' an more "advanced" version with a user interface

note that the emulator should be working with boths

NOTE: Emulators done, main file is to profile according to needs of the project
