== Project description
The project is focusing around the Power consumption of a control card.
The code as the objective of driving different element to evaluate this consumption.

== Objective
With the driving of the different device, we can evaluate the power consumption of the control card.
One application exemple is from the project OWL : https//owl.univ-nantes.fr

== Devices used
The code as been profiled to work with the following devices :

* A TENMA progammable power supply, drivable to set a needed level of voltage, look ``Emulator/PSemu.py``
** Code are in majority from https://github.com/mbriday/PVEmu/tree/main
* The Power Profiler Kit 2 from Nordic, which include an onboard amperemeter, look ``Emulator/PPKemu.py``
* A Keysight Oscilloscope, model DSOX1204G, for tension mesurement, look ``Emulator/OSCIemu.py``

== Main files
There is two main file:

* ``Main.py`` a simpler version to show how emulators are used
* ``Main_UI.py`` an more "advanced" version with a user interface

note that the emulator should be working with boths

NOTE: in ``Emulator/OSCIemu.py`` the serial connection is established with a precise name for the device. It may be a differant one for yours.
