== Project description
The project is focusing around the consumption of a control card, the Apollo 4 model.
This card is being use in order to record populations of birds.

== Objective
The objective is to replace the battery as less as possible, to avoid disturbing those populations 
A method proposed come from the project EARLYBIRD https://hal.science/hal-04663862v1

== Devices used
In order to work with the Apollo card, multiple devices were used:

* A TENMA progammable power supply, capable of providing level of voltage required for the card, see ``Emulator/PSemu.py``
** Code are in majority from https://github.com/mbriday/PVEmu/tree/main
* The amperemeter included in the Power Profiler Kit 2 from Nordic, see ``Emulator/PPKemu.py``
* A Keysight Oscilloscope, model DSOX1204G, for tension mesurement, see ``Emulator/OSCIemu.py``

== Main files
There is two main file:

* ``Main.py`` a simpler version to show how emulators are used
* ``Main_UI.py`` an more "advanced" version with a user interface

note that the emulator should be working with boths

NOTE: The UI version is imcomplete, oscilloscope not fully implemented
